---
- name: install redis-server
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: copy redis config
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: root
    mode: 0600

- name: restart redis server
  service:
    name: redis-server
    state: restarted
    enabled: yes
